# Generated by Django 4.2.6 on 2024-05-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Designates if user is used to demo website content'),
        ),
    ]
