# Generated by Django 4.2.6 on 2023-11-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='files',
            field=models.JSONField(blank=True),
        ),
    ]
