# Generated by Django 4.2.6 on 2023-11-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0002_alter_sandbox_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='files',
            field=models.JSONField(null=True),
        ),
    ]
