# Generated by Django 4.2.6 on 2023-11-20 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0004_alter_sandbox_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='files',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='title',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Enter a valid sandbox title. This value may contain only unaccented lowercase a-z and uppercase A-Z letters, numbers, and @/./+/- characters.', regex='^[\\w.@+-]+\\Z')]),
        ),
    ]
