# Generated by Django 4.2.6 on 2024-02-19 18:31

from django.conf import settings
from django.db import migrations, models
import sandbox.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sandbox', '0006_alter_sandbox_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='stared_user',
            field=models.ManyToManyField(related_name='starred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='files',
            field=models.JSONField(default=sandbox.models.get_default_files),
        ),
    ]
