# Generated by Django 4.2.6 on 2024-02-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0007_sandbox_stared_user_alter_sandbox_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sandbox',
            old_name='stared_user',
            new_name='starred_users',
        ),
    ]
