# Generated by Django 4.2.6 on 2024-05-01 17:02

from django.db import migrations, models
import sandbox.models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0008_rename_stared_user_sandbox_starred_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sandbox',
            name='preview',
            field=models.ImageField(default='', null=True, upload_to=sandbox.models.sandbox_preview_path),
        ),
    ]
