# Generated by Django 4.2.6 on 2024-05-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0009_sandbox_is_demo_sandbox_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandbox',
            name='is_demo',
        ),
    ]
