# Generated by Django 4.2.6 on 2024-05-01 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sandbox', '0010_remove_sandbox_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='starred_users',
            field=models.ManyToManyField(null=True, related_name='starred', to=settings.AUTH_USER_MODEL),
        ),
    ]
