# Generated by Django 4.2.6 on 2024-05-02 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sandbox', '0011_alter_sandbox_starred_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='starred_users',
            field=models.ManyToManyField(related_name='starred', to=settings.AUTH_USER_MODEL),
        ),
    ]
